"""Add delivery status and attempt fields to Generation

Revision ID: 127012017373
Revises: 6733cd39469b
Create Date: 2026-10-03 04:13:36.616879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127012017373'
down_revision: Union[str, Sequence[str], None] = '6733cd39469b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('delivery_status', sa.Enum('not_delivered', 'in_progress', 'delivered', 'failed', name='delivery_status', native_enum=False, length=16), nullable=True))
    op.add_column('generations', sa.Column('delivery_attempt_id', sa.String(length=36), nullable=True))

    # Заполняем существующие записи дефолтным значением
    op.execute("UPDATE generations SET delivery_status = 'not_delivered' WHERE delivery_status IS NULL")

    # Делаем колонку NOT NULL
    op.alter_column('generations', 'delivery_status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'delivery_attempt_id')
    op.drop_column('generations', 'delivery_status')
    # ### end Alembic commands ###
