"""Add audio storage fields to generations

Revision ID: 2587720930f1
Revises: 83bf72827fe6
Create Date: 2026-09-29 20:33:40.191151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2587720930f1'
down_revision: Union[str, Sequence[str], None] = '83bf72827fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('audio_path', sa.String(length=512), nullable=True))
    op.add_column('generations', sa.Column('audio_size', sa.BigInteger(), nullable=True))
    op.add_column('generations', sa.Column('audio_checksum', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'audio_checksum')
    op.drop_column('generations', 'audio_size')
    op.drop_column('generations', 'audio_path')
    # ### end Alembic commands ###
