"""init

Revision ID: 6f9f397b3535
Revises: 
Create Date: 2026-09-23 05:14:43.337053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9f397b3535'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('generation_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('initial_prompt', sa.Text(), nullable=False),
    sa.Column('enriched_prompt', sa.Text(), nullable=False),
    sa.Column('is_liked', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_feedbacks_user_id'), 'generation_feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_feedbacks_user_id'), table_name='generation_feedbacks')
    op.drop_table('generation_feedbacks')
    op.drop_table('users')
    # ### end Alembic commands ###
