"""add_processing_status_and_attempt_id

Revision ID: 83bf72827fe6
Revises: f55bf4af599c
Create Date: 2026-09-29 06:54:20.560914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bf72827fe6'
down_revision: Union[str, Sequence[str], None] = 'f55bf4af599c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('attempt_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'attempt_id')
    # ### end Alembic commands ###
