"""add_index_gen_id

Revision ID: a04004b622f5
Revises: 9b0578c8951f
Create Date: 2026-09-28 05:28:57.871048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04004b622f5'
down_revision: Union[str, Sequence[str], None] = '9b0578c8951f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_feedbacks_generation_id'), table_name='generation_feedbacks')
    op.create_index(op.f('ix_generation_feedbacks_generation_id'), 'generation_feedbacks', ['generation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_feedbacks_generation_id'), table_name='generation_feedbacks')
    op.create_index(op.f('ix_generation_feedbacks_generation_id'), 'generation_feedbacks', ['generation_id'], unique=False)
    # ### end Alembic commands ###
