"""add_composite_index_on_generations

Revision ID: d7abe2ef709a
Revises: a04004b622f5
Create Date: 2026-09-28 05:33:43.626874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7abe2ef709a'
down_revision: Union[str, Sequence[str], None] = 'a04004b622f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_generations_user_status_created', 'generations', ['user_id', 'status', 'created_at'], unique=False, postgresql_where=sa.text("status = 'success'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generations_user_status_created', table_name='generations', postgresql_where=sa.text("status = 'success'"))
    # ### end Alembic commands ###
