"""add title to generation_feedbacks

Revision ID: e2f1d25825c6
Revises: 6f9f397b3535
Create Date: 2026-09-24 00:07:45.768749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f1d25825c6'
down_revision: Union[str, Sequence[str], None] = '6f9f397b3535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_feedbacks', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_feedbacks', 'title')
    # ### end Alembic commands ###
