"""fix_composite_index_remove_partial

Revision ID: f55bf4af599c
Revises: d7abe2ef709a
Create Date: 2026-09-28 05:36:56.277855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55bf4af599c'
down_revision: Union[str, Sequence[str], None] = 'd7abe2ef709a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
